### ISSUE TITLE
Turning off LLVM profiling or code coverage with CI/Fastlane

### ISSUE THREAD

**Issue by i-schuetz** [Carthage/Carthage#2196]
(CircleCI environment)

* `carthage version`: 0.25.0
* `xcodebuild -version`: Xcode 9.0, Build version 9A235

circle.yml:
```
...
dependencies:
  pre:
    - gem update fastlane
  override:
    - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
    - bin/bootstrap-if-needed
    - brew install swiftlint
  cache_directories:
    - vendor/bundle
    - Carthage
...
```

bootsrap-if-needed:
```
#!/bin/sh

if ! cmp -s Cartfile.resolved Carthage/Cartfile.resolved; then
  bin/bootstrap
fi
```
(Note: Also tried replacing the `bootsrap-if-needed` script with the fastlane step described in stackoverflow post linked below)

-----------

Always receiving this message from Apple on submission:

"Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app."

I followed all the solutions provided in #2056, no changes. Concretely I ensured that my app and dependencies (in the original repos) don't have any coverage flags enabled (they had some but in targets which I don't use like macOS).

I'm using CircleCI / Fastlane.

I also added a script to set `codeCoverageEnabled` to `NO` to the build file, like described in this [Stackoverflow answer](https://stackoverflow.com/a/46226810/930450) - also no improvement!

It only worked when building locally / uploading the build manually. I don't know why.

How do I get the Fastlane/CircleCI release working?
